before_install:
    - docker build -t nickolu/docker-training -f Dockerfile.dev .

script:
    - docker run -e CI=true nickolu/docker-training npm run test

deploy:
    provider: elasticbeanstalk
    region: "use-east-2"
    app: "docker-training"
    env: "DockerTraining-env"
    bucket_name: "elasticbeanstalk-us-east-2-914758622339"
    bucket_path: "docker-training"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
